### ISSUE TITLE
Capture images from device

### ISSUE THREAD

**Issue by luca18** [IntelRealSense/RealSenseID#106]
I tested out the new SDK v0.23.0 on Ubuntu 18. When I launched the rsid-cli like usually, I noticed that there is a new option added for the device mode. The new option is listed as:

    'c' to capture images from device.

When I run this option, I get the following displayed:

    frame #0: 1056x1920 (6082560 bytes)
    frame #1: 1056x1920 (6082560 bytes)
    frame #2: 1056x1920 (6082560 bytes)
                           :
                           :
    frame #43: 1056x1920 (6082560 bytes)

I'm not sure how this new feature works and I found little to no help in the source code or on the github page.
Could someone help me with enrolling a user in device mode with a .png portrait image that I have saved on my computer on Ubuntu?

Thanks in advance.

**Comment by gabime** [comment]
Please seem the [enroll_image.py](https://github.com/IntelRealSense/RealSenseID/blob/master/samples/python/enroll_image.py) sample.
