### ISSUE TITLE
Authenticate in host mode (python)

### ISSUE THREAD

**Issue by Monica2511** [IntelRealSense/RealSenseID#118]
Hi, I want to use device in host mode with python. I know f455 can extract faceprints data and store in host but how to extract faceprints data with python and create db file. Pls give me solution for this, many thanks.

**Comment by gabime** [comment]
Hi

Please take a look at the [host_mode.py](https://github.com/IntelRealSense/RealSenseID/blob/master/samples/python/host_mode.py) sample. It demonstrates extracting and storing the faceprints to memory using python. To save to real DB, you can serialize the faceprints object in any way you see fit as long as all its members are preserved :
```python 

adaptive_descriptor_nomask
adaptive_descriptor_withmask
enroll_descriptor
features_type
flags
reserved
version
```
