### ISSUE TITLE
Preview is very dark

### ISSUE THREAD

**Issue by nickticket2u** [IntelRealSense/RealSenseID#12]
Hello people.

Just wonder why the camera's PreviewImage returned is very dark, like almost pitch black. I've switch on all the lights, face a flashlight on my face, it is still extremely dark. I see that it has some bluish tint, maybe that's the reason.

Tried with the c# example. Same with my own project.

It will ID correctly though.

Any help is greatly appreciated

-EDIT-

after calling _authenticator.Authenticate, it becomes very dark. Only after a long while, it gets brighter a bit.

-2ND EDIT-

point to a black shirt, click Authenticate, the preview becomes dark. Points to a white object, click Authenticate, the preview becomes bright a bit. There's something "off" about the white balance/metering somehow

**Comment by nickticket2u** [comment]
point to the white air conditioner, click Auth. preview then becomes a bit bright
![image](https://user-images.githubusercontent.com/63834394/110319907-7c85a280-804a-11eb-8dd5-d55259289ce3.png)

Points to a dark place, click Auth. Then point back to myself. Preview then becomes dark

![image](https://user-images.githubusercontent.com/63834394/110320011-a0e17f00-804a-11eb-907b-173761b1dc5e.png)

**Comment by RealSenseSupport** [comment]
Hi @nickticket2u 

Thanks for submitting this issue.  We will have a look into this and let you know what we find out.

Just to confirm again, you're not seeing an issue with authenticate even though the preview looks like this?

**Comment by nickticket2u** [comment]
thanks for the response.
yeah authenticate works fine.

**Comment by 3dsf** [comment]
hey @nickticket2u  

I've been watching your ticket, as I recognise value in the preview feature.

Just a heads up, instead of doing edits to the first post, it might be better to make new comments, as they would alert the people involved with this project with the further information related to this issue.  
On a platform such as reddit, the edits in the post work well because you are counting on continual new viewers.

**Comment by ShravyaB** [comment]
I have observed an opposite behaviour. I was testing a backlight situation but this occurs in a well lit situation too. When a person enters the frame (even if it is far) there is higher exposure compensation done (light in the background gets bloated). Is this done on purpose?

**Comment by 3dsf** [comment]
@nickticket2u

Does RealSenseID/releases/tag/v0.15.0 resolve the issue for you ?

**Comment by nickticket2u** [comment]
Will have time to try it next week 🙏😁

**Comment by nickticket2u** [comment]
problem is solved with latest firmware
