### ISSUE TITLE
test issue for bridge test

### ISSUE THREAD

**Issue by timor-raiman** [IntelRealSense/RealSenseID#13]
opening comment of test 1

**Comment by RealSenseCustomerSupport** [comment]
----------------------------------------------

public reply 2

**Comment by timor-raiman** [comment]
comment from github 1

**Comment by timor-raiman** [comment]
issue closed in github closing comment 1

**Comment by RealSenseCustomerSupport** [comment]
----------------------------------------------

public reply after solved 2

**Comment by timor-raiman** [comment]
re-opening comment 1

**Comment by timor-raiman** [comment]
closing coment 2

**Comment by timor-raiman** [comment]
closing coment 3

**Comment by timor-raiman** [comment]
re-opening comment 3

**Comment by timor-raiman** [comment]
closing comment 4

**Comment by timor-raiman** [comment]
re-opening comment 4

**Comment by timor-raiman** [comment]
re-opening comment 5

**Comment by timor-raiman** [comment]
re-opening comment 6

**Comment by timor-raiman** [comment]
re-opening comment 7
