### ISSUE TITLE
Ubuntu 20.04.3/ Linux Kernel 5.11 Support

### ISSUE THREAD

**Issue by labusaid** [IntelRealSense/RealSenseID#130]
My realsense d435i camera drivers have not been reliable on kernel 5.11 which I need in order to support my rx6600xt GPU. I was wondering if there are plans to officially support the new kernel now that Ubuntu LTS has adopted it or if there's a know workaround to get the d435i working consistently on 5.11.

**Comment by 3dsf** [comment]
just curious, 

- what was your install method?
- what's the issue?
- can you share the code you are running?

**Comment by RealSenseSupport** [comment]
Hi @labusaid This is RealSenseID (F450/F455, not D400) forum. Please post the issue on https://github.com/IntelRealSense/librealsense/issues.
Thanks.
