### ISSUE TITLE
function EnrollImage with error "SWIGTYPE_p_unsigned_char buffer" [ANDROID]

### ISSUE THREAD

**Issue by tmq902005** [IntelRealSense/RealSenseID#139]
Hi all,
function EnrollImage & EnrollImageFeatureExtraction with parameter SWIGTYPE_p_unsigned_char buffer

![image](https://user-images.githubusercontent.com/21018215/153373559-252afc8e-5412-466c-b698-52ff09629dfc.png)

**Comment by RealSenseSupport** [comment]
I think it should be an issue about swig.
This commit may be useful.
https://github.com/mengyui/RealSenseID/commit/60e8725123524137cd9520fbf7a527533d42fa6f
