### ISSUE TITLE
Publish API Reference on Web

### ISSUE THREAD

**Issue by UnaNancyOwen** [IntelRealSense/RealSenseID#15]
API Reference for RealSense ID SDK (generated by doxygen) is not publicly available.  
Please publish API Reference on Web like [RealSense SDK](https://intelrealsense.github.io/librealsense/doxygen/index.html).  
I'm temporarily publish API Reference on Web, but it is unofficial.
By all rights, It should be publish officially by RealSense ID team. Thanks,
https://unanancyowen.github.io/realsenseid_apireference/

**Comment by gabime** [comment]
The doxygen is available in the release page (https://github.com/IntelRealSense/RealSenseID/releases/download/v0.13.0/rsid_api_docs.zip)

**Comment by UnaNancyOwen** [comment]
@gabime That's great, however it is local file. Even better if it published on web page!

**Comment by RealSenseSupport** [comment]
Thanks @UnaNancyOwen - Maybe we will be able to get to publishing on web but for now the zip will continue.
