### ISSUE TITLE
License Questions

### ISSUE THREAD

**Issue by mdisg** [IntelRealSense/RealSenseID#155]
Can you please give us some detail information how the licensing works?

- How often will the license check happen?
- As seen in the source the license status is checked via REST using the endpoint url `https://visionplatform.intelrealsense.com/v2/f450/license-status` not all customers allow direct access to internet resources so how to use the device in complete offline mode with the new firmware? If access to the web is required then this would prevent usage of the devices in offline environments.
- There are different kind of licenses listed in [LicenseChecker.h](../blob/master/src/LicenseChecker/LicenseChecker.h) like `FACIAL_AUTH_SUBSCRIPTION` what is the difference between them? The official store only lists a 1-year license but no details about it or what other license variants are available.
- is it possible to get one license key that can be used for multiple devices or does every device get a unique device associate key?
- if the 1 year period comes to the end will the license key change or will it be usable again after the license is renewed?

@MartyG-RealSense can you give some insight?

**Comment by sherrysun2018** [comment]
@mdisg Currently, 1-year facial authentication license is available via the online store. For special license requirement, please contact https://www.intel.com/content/www/us/en/forms/support/intel-realsense-store-inquiry.html
It is possible that one license key is used for multiple devices. 
The same product key can be reused after the license is renewed.

**Comment by mdisg** [comment]
@sherrysun2018 thanks for your information. We already have contacted one of your sale representative but got no clear answer about the lifetime lisence. They told us that it may be possible but kept it unclear about what are the requirements to get it. Do you have more information?

**Comment by sherrysun2018** [comment]
@mdisg You can check with our sale representative for more details about lifetime license. And can we close this ticket now? Thanks!

**Comment by mdisg** [comment]
@sherrysun2018 you can close it. Thanks!
