### ISSUE TITLE
authentication error at application startup

### ISSUE THREAD

**Issue by rifai-github** [IntelRealSense/RealSenseID#156]
a few days ago I bought an Intel RealSense F455 at this link https://store.intelrealsense.com/intel-realsense-id-solution-f455-peripheral-version-with-software.html.

I've tried it but why do I get an error?
this is the error:
![Screenshot 2024-05-27 115112](https://github.com/IntelRealSense/RealSenseID/assets/22672977/dba46571-ebfa-43bf-a1c1-118f26075c89)

**Comment by sherrysun2018** [comment]
@rifai-github Did you register the product key?

**Comment by RealSenseCustomerSupport** [comment]
----------------------------------------------

@rifai-github Did you have chance to register the product key? Looking forward to your reply. Thanks!

**Comment by RealSenseCustomerSupport** [comment]
----------------------------------------------

@rifai-github Do you still have issue? Could you please update? Thanks!

**Comment by RealSenseCustomerSupport** [comment]
----------------------------------------------

@rifai-github  We didn't hear from you for several months. Will close this ticket at this point. If you still have issue, please feel free create another ticket. Thanks!
