### ISSUE TITLE
Generate config.cmake files for generate user projects using CMake

### ISSUE THREAD

**Issue by UnaNancyOwen** [IntelRealSense/RealSenseID#16]
Please generate config.cmake files for generate user projects using CMake.  
Many modern libraries provide cmake/***Config.cmake file for users to find library and configure to project using CMakeLists.  
Currently, CMake files of RealSense ID SDK does not generate it.

**Comment by UnaNancyOwen** [comment]
@gabime Do RealSense ID team have a plan to fix this issue yourself? (I'm concerned because related pull request #24 send from community has been closed by you.)

**Comment by gabime** [comment]
@UnaNancyOwen Yes, we plan to add this in one of the next releases.

**Comment by UnaNancyOwen** [comment]
@gabime It's good! Thanks, 👍

**Comment by gabime** [comment]
Released in v0.15.0. Use `cmake -DRSID_INSTALL=ON` to enable.
