### ISSUE TITLE
RealSense ID SDK does not install by CMake

### ISSUE THREAD

**Issue by UnaNancyOwen** [IntelRealSense/RealSenseID#17]
Currentry, RealSense ID SDK does not install by CMake.
In general, the build files generated by CMake can generate INSTALL projects and install libraries. (cmake --build . --target install)
CMake files of RealSense ID SDK is missing scripts for this purpose.
(This issue is related to https://github.com/IntelRealSense/RealSenseID/issues/16)

Reference : 
https://github.com/IntelRealSense/librealsense/blob/master/CMake/install_config.cmake
https://cmake.org/cmake/help/latest/guide/tutorial/index.html#adding-export-configuration-step-11
https://cliutils.gitlab.io/modern-cmake/chapters/install.html

**Comment by RealSenseSupport** [comment]
Hi @UnaNancyOwen 

Is there anything further you need on this thread?

**Comment by UnaNancyOwen** [comment]
@RealSenseSupport RealSense ID team working on related problem. It will be resolved with this issue shortly. 👍  https://github.com/IntelRealSense/RealSenseID/issues/16#issuecomment-803854474

**Comment by RealSenseSupport** [comment]
Thanks for pointing this out...yes we are monitoring that one too.

**Comment by gabime** [comment]
Released in v0.15.0. Use cmake -DRSID_INSTALL=ON to enable.
