### ISSUE TITLE
self-built rsid_csharp_example from source code does not display preview

### ISSUE THREAD

**Issue by UnaNancyOwen** [IntelRealSense/RealSenseID#22]
The self-built rsid_csharp_example from source code does not display preview. The pre-built RealSense ID Viewer included in installer is works fine. All other functions are working fine. But, preview is not display.
![2021-03-16_16h57_39](https://user-images.githubusercontent.com/816705/111274976-fa643200-8678-11eb-831c-e0f89d8488f7.png)

<code>_preview.Start(OnPreview);</code> returns False.
https://github.com/IntelRealSense/RealSenseID/blob/v0.13.0/examples/csharp_example/MainWindow.xaml.cs#L1159

Could you give me some advice? Thanks,

**Comment by gabime** [comment]
To build with preview support, use the  ```-DRSID_PREVIEW=ON``` CMake option (and install opencv).

Please refer to the instructions in https://github.com/IntelRealSense/RealSenseID/tree/master/examples#how-to-build

**Comment by UnaNancyOwen** [comment]
@gabime Thanks! I had missed that one. It works fine. :)
