### ISSUE TITLE
How can I use score in MatchFaceprints function.

### ISSUE THREAD

**Issue by donghyun999** [IntelRealSense/RealSenseID#25]
I want to use the score value used in the MatchFaceprints function.
Because in a database containing 20 faceprints, it's sometimes recognized as someone else. 
So I want to get the score and choose the person with the highest score out of 20 people.

**Comment by UnaNancyOwen** [comment]
I think so too. Currently, there is no way to get the internally calculated score. It only display in the logs.
@gabime What do you think? Thanks,

**Comment by alexk1976** [comment]
@donghyun999 it shouldn't happen. I want to debug and fix your issue. Maybe your faceprints from different FW versions? Can you re-enroll and reproduce using latest FW/app?
Regarding exposing score...we can do it but not sure it'll help you. We run huge benchmarks to calculate the score (threshold) to optimize FPR vs TPR values. I dont think you have ability to calculate required score. Am i wrong?

**Comment by donghyun999** [comment]
We want to find the person with the highest score, can't we just use the score value?

**Comment by alexk1976** [comment]
I see. we'll expose it in next version. If it's urgent ..you can do it yourself in MatchResult Matcher::MatchFaceprints() function. Add maxScore to MatchResult struct

**Comment by donghyun999** [comment]
I think we can proceed with good development.
thank you for resposce

**Comment by donghyun999** [comment]
i have a new question

**Comment by donghyun999** [comment]
i have a new question

Face authentication succeeds if you only wear a mask, and face authentication succeeds when you wear a different hair style without wearing a mask. On the other hand, face authentication fails when wearing a mask and wearing a different hairstyle.

In this case, I think hairstyles also affect facial verification. I wonder why this happens.

![image](https://user-images.githubusercontent.com/70622902/112826155-935a6a80-90c7-11eb-9a7e-d8d8aaf6d334.png)
![test2](https://user-images.githubusercontent.com/70622902/112826166-96edf180-90c7-11eb-95d9-890cab46bbb3.png)
![test4](https://user-images.githubusercontent.com/70622902/112826195-a10ff000-90c7-11eb-9873-84ccc35cf482.png)
![test6](https://user-images.githubusercontent.com/70622902/112826207-a5d4a400-90c7-11eb-9663-3419f4ef07f4.png)
![test7](https://user-images.githubusercontent.com/70622902/112826212-a79e6780-90c7-11eb-91d0-fe0c5abe3cf0.png)

**Comment by alexk1976** [comment]
long hair might be in face area and captured along with other facial features. When only one part (mask or hair) changes ..the distance (match score) to original enrollment is still close and match is succeeded. When a few facial parts change the match score is not close enough and it fails. In next releases we'll introduce adaptive learning feature that will update original enrollment data and allow more facial feature changes on the way
