### ISSUE TITLE
Compiling for ARM Linux / Support

### ISSUE THREAD

**Issue by mdisg** [IntelRealSense/RealSenseID#29]
Is RealSenseID SDK supported under ARM linux?

If so, how can I compile the library for an ARM based linux like an embedded system (e.g. buildroot/yocto)?

**Comment by nickticket2u** [comment]
I did it on Raspberry Pi (ARM Linux)
just install cmake and g++ (or gcc  I can't recall).
go to src folder, type cmake ..
then type make -j
then it will generate librsid_c.so and librsid.so files
I was able to load the so file in my .net core linux arm project

**Comment by mdisg** [comment]
@nickticket2u thanks but unfortunately that will not work for my case because my device does not have that much space to install build tools on it and buildroot does only provide the build tools for the host environment. I have to cross compile it using a toolchain released by the manufacturer.

**Comment by nickticket2u** [comment]
I'm not well versed about all these arm linux thing. are these *.so files portable between arm linux systems ? the .so file itself is small

**Comment by mdisg** [comment]
I think it depends on the libc/kernel version etc. on the device so it may not be compatible.

**Comment by gabime** [comment]
> Is RealSenseID SDK supported under ARM linux?

No. However you can try to  compile/cross-compile it to your platform.

**Comment by mdisg** [comment]
I managed to compile the examples without the preview feature.

If anyone else wants to cross compile I used a separate cmake file (toolchain-arm.cmake) containing the following variables:

```
SET(CMAKE_C_COMPILER   /path_to/arm-linux-gnueabi-gcc)
SET(CMAKE_CXX_COMPILER /path_to/bin/arm-linux-gnueabi-g++)
SET(CMAKE_FIND_ROOT_PATH  /path_to/target)
SET(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
SET(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
SET(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)
```

Provide the toolchain to cmake with the following argument `-DCMAKE_TOOLCHAIN_FILE=toolchain-arm.cmake`

Could be useful for others if that information is added to the building instructions?

**Comment by gabime** [comment]
@mdisg  That's great.  Could you provide more details on the platform it runs ?

**Comment by mdisg** [comment]
@gabime sure it's an i.MX6 (ARM Cortex-A9) with 2 Cores and 512MB of RAM.
The linux system is build using buildroot with Kernel 4.9.88

I did some tests with the example c program. Sometimes there seems to be a serial communication issue e.g. reading the user ids from the device failes from time to time but if repeated right after a failure that it succeeds.  I will keep an eye on that.

Offtopic question is there a way to enroll/add users to the device with already recorded faceprints so that authentication can be done by the device? We want to enroll users on one of our devices with the real sense unit but spread it across many devices also having a real sense unit for authentication. I know there is host mode but I'm unsure about the performance if there are a lot of faceprints in the host database.

**Comment by nickticket2u** [comment]
that's a good question, regarding the enrolling faceprints data

**Comment by gabime** [comment]
> Offtopic question is there a way to enroll/add users to the device with already recorded faceprints

Currently there is not such feature in the library

**Comment by alexk1976** [comment]
we have it in plan

**Comment by mdisg** [comment]
@alexk1976 great! Can you give me a time range when it will likely be available?

Yesterday I tried to compile the SDK with the preview feature with opencv Version 4.3.0 which works for the librarys itself but not for the examples. It failes to link because it cannot find the opencv librarys. I could not figure it out why it does not find them.

I have added the opencv library path (separate folder) in `CMAKE_FIND_ROOT_PATH` and `CMAKE_LIBRARY_PATH` but both did not solve it.

**Comment by KennyDizi** [comment]
looking forward the SDK support ARM Linux (run on AIoT motherboard)

**Comment by RealSenseSupport** [comment]
Hi @mdisg 

Have you tried the latest release? Additional changes to support cross platform compatibility have been introduced since.

Thanks

**Comment by mdisg** [comment]
@RealSenseSupport There is nothing mentioned in the release notes. What exactly has change for cross platform compatibility? Do you mean the removal of opencv? If that's the case that was a good choice. Compiling the latest `0.17.0` SDK was possible using my existing toolchain cmake file. No errors in compiling the samples.

**Comment by gabime** [comment]
>  What exactly has change for cross platform compatibility?
 
Indeed OpeNCV dependency was removed, and also removed the dependency on mutexes so it can now compiled in environments without proper thread support.
