### ISSUE TITLE
sometimes preview image is very dark

### ISSUE THREAD

**Issue by UnaNancyOwen** [IntelRealSense/RealSenseID#30]
Sometimes preview image is very dark.
Once it goes dark, it will stay dark until the next time authentication.
I think this problem related automatic exposure with IR flash light.
It seems automatic exposure does not work well.
I want that even if it gets dark image for a while it will soon recover proper exposure.
Can anyone reproduce this problem? and, Is it possible to fix this problem by updating firmware?
Thanks,

**Comment by UnaNancyOwen** [comment]
related https://github.com/IntelRealSense/RealSenseID/issues/12

**Comment by alexk1976** [comment]
You are right. latest drop not using auto-exposure for preview. Auto-exposure drop is expected on this Thursday

**Comment by RealSenseSupport** [comment]
Hi @UnaNancyOwen 

Have you tried the 0.15.0 SDK release https://github.com/IntelRealSense/RealSenseID/releases/tag/v0.15.0 that now has auto exposure enabled?

**Comment by UnaNancyOwen** [comment]
Yes, It seems to be works fine! Thanks,
