### ISSUE TITLE
[feature request] Support for Windows Hello Face

### ISSUE THREAD

**Issue by pawseytj** [IntelRealSense/RealSenseID#34]
I realise this is an SDK but daily use is a great way to test.  Any chance the SDK can support Windows Hello Face, or is there anyone that can provide software I can install to make this work.  I am just a dumb end user and purchased Intel RealSense ID solution F455 in the hope of developers adding such a feature I could use (download & install, then plug-and-play setup).

**Comment by RealSenseSupport** [comment]
Hi @pawseytj 

Thanks for purchasing the product.  There are no plans to officially support Windows Hello.  From Intel perspective, final complete solutions outside of the SDK will be done by 3rd party vendors.  Intel is making the hardware available for purchase and the SDK open source for the developer community to design and develop solutions on top of the SDK.
