### ISSUE TITLE
Python binding

### ISSUE THREAD

**Issue by iscsrl** [IntelRealSense/RealSenseID#35]
I'm trying to implement a python binding with pybind11 but I'm stuck with this two issues.

If I run with Python2 I get:
undefined symbol: _ZN11RealSenseID17FaceAuthenticator7StandbyEv

If I run with Python3 I get:
Segmentation fault (core dumped)

Do you already have any python binding available? When the official sdk for python will be released?

**Comment by RealSenseSupport** [comment]
Hi @iscsrl 

At this time we do not have Python support.  We cannot comment on future release schedules at this time.
