### ISSUE TITLE
Can you example for extract faceprint for Android?

### ISSUE THREAD

**Issue by tmq902005** [IntelRealSense/RealSenseID#36]
I have seen an example project for Android but don't see the face print extract. Because I want to match it on the external server.

**Comment by Gilaadb** [comment]
Hello @tmq902005. You are right, the faceprints API was not wrapped for Android in our latest public version, but I believe it will be in the next version we release.
For the time being there are no plans to add it to the example Android application, but once the version with the missing wrapper will be released, extracting faceprints in Android should be pretty straight forward.

**Comment by tmq902005** [comment]
Thank you, @Gilaadb
