### ISSUE TITLE
Max people enrolled

### ISSUE THREAD

**Issue by santicomp2014** [IntelRealSense/RealSenseID#37]
I have a doubt about the max amount of people you can recognize with F455.

Is 1000 hard coded into the device and is this limitation also applied in host mode.

If I extract the face points, I can store them somewhere else and have more than 1000 faces?.

Thanks.

**Comment by alexk1976** [comment]
In device mode indeed we have 1000 limitation due to memory constraints. In host side no reason for such limitation and user/app can manage 10k users easily. where did you see any limit in host mode?
