### ISSUE TITLE
How can I get wearing mask status and the location of the face?

### ISSUE THREAD

**Issue by donghyun999** [IntelRealSense/RealSenseID#38]
We do face verification with F455.

it is influenced a lot by wearing a mask.

If you wear a mask, other people's scores can be recognized as a threshold.

So we wonder if there is a way to know if a person is wearing a mask and where the face is in the picture.

**Comment by RealSenseSupport** [comment]
Hi @donghyun999 

Can you provide image of the scenario that you are outlining?  That way we have a better understanding of your question and/or feature request.

**Comment by donghyun999** [comment]
![2021-04-08_15_09_43_enroll_동현](https://user-images.githubusercontent.com/70622902/115339742-570abd80-a1e0-11eb-8e57-8a76a3225e0c.png) <wearing mask>
![123](https://user-images.githubusercontent.com/70622902/115339745-596d1780-a1e0-11eb-87a1-8208167d11a5.png) <none wearing mask>
if you're wearing a mask or not.
