### ISSUE TITLE
Firmware ERRO: What do I do?

### ISSUE THREAD

**Issue by cabelo** [IntelRealSense/RealSenseID#47]
The new release does not work without updating the firmware. But when I update this error of the images occurs.

![image](https://user-images.githubusercontent.com/675645/116339176-5c08d780-a7b3-11eb-829c-4feab1c3359b.png)

![image](https://user-images.githubusercontent.com/675645/116339236-717e0180-a7b3-11eb-838b-9c300d6ee5c0.png)

![image](https://user-images.githubusercontent.com/675645/116339257-7d69c380-a7b3-11eb-9ed1-f3373e8f6023.png)

![image](https://user-images.githubusercontent.com/675645/116339283-8a86b280-a7b3-11eb-83d2-cf832a3f6b93.png)

**Comment by alexk1976** [comment]
Please use latest SDK and upgrade to bundled FW
Let me know if the issue still exists

**Comment by cabelo** [comment]
Hi @alexk1976 Problem continues, below the evidence.
![p01](https://user-images.githubusercontent.com/675645/117929392-24ca1880-b2d3-11eb-8965-97a65fc73ad8.jpg)
![p02](https://user-images.githubusercontent.com/675645/117929395-2693dc00-b2d3-11eb-8adb-87668e9e867c.jpg)
![p03](https://user-images.githubusercontent.com/675645/117929406-28f63600-b2d3-11eb-898a-ea1149710e5b.jpg)

**Comment by benlev** [comment]
Hi @cabelo, it looks like you paired your device after compiling with RSID_SECURE=1. This is done automatically when running the rsid-viewer tool, or manually, if you use the rsid-cli tool.

If you used the sample set of keys, you can simply re-compile with RSID_SECURE=1 and try again. However, if you paired with your own set of keys, you must use them.

To be able to work with the unit with RSID_SECURE=0, you must first unpair the device. To do so, run the rsid-cli sample and select 'i'. Again, this should be done with the set of keys you used when pairing.

Let me know if this works out for you.

-Ben

**Comment by cabelo** [comment]
Ok  @benlev 

I'm going to do this, do you prefer this test of RSID_SECURE = 0 in linux or windows?

But I would like to clarify, that I used only this installer program : rsid_sdk_v0.17.1_win64.exe

**Comment by cabelo** [comment]
Hi @benlev 

I build  RSID_SECURE=0 on the linux, bellow see the erros

![image](https://user-images.githubusercontent.com/675645/118078997-a4b4b900-b38d-11eb-917a-65b3545ccbe8.png)

![image](https://user-images.githubusercontent.com/675645/118079018-ad0cf400-b38d-11eb-947c-2e3ca2979dd0.png)

**Comment by benlev** [comment]
@cabelo, please try the following:
1. Compile with RSID_SECURE=1.
2. Run 'rsid-cil' and select 'p' to pair with the device.
3. Try enrollment/authentication - should now work.
4. Select 'i' to unpair the device.
5. Re-compile with RSID_SECURE=0.
6. Run 'rsid-cli' and try enrollment/authentication.

-Ben

**Comment by cabelo** [comment]
@benlev 

Initially I tested it in Realsense ID Viewer to test the functionality and do not run the risk of having problems.

I recompiled with the parameter RSID_SECURE = 1 and everything worked on linux, but in the Realsense ID Viewer program on Windows the problem continues.
I will particularly work only on Linux, but I think it would be interesting for everything to work on both platforms.

If I had started on Linux, I wouldn't have even opened this request.
I will particularly work only on Linux, but I think it would be interesting for everything to work on both platforms.

If I had started on Linux, I wouldn't have even opened this request.

Below the evidence, thank you.

First In Linux:

![image](https://user-images.githubusercontent.com/675645/118428940-efdd0d80-b6a6-11eb-8e3b-dfeac2ba07cc.png)

![image](https://user-images.githubusercontent.com/675645/118428979-071bfb00-b6a7-11eb-9c90-140054e46018.png)

![image](https://user-images.githubusercontent.com/675645/118429013-18fd9e00-b6a7-11eb-964c-8e8946b7a394.png)


But... In Windows...

![image](https://user-images.githubusercontent.com/675645/118429081-3fbbd480-b6a7-11eb-9b68-70237f40fd2a.png)

**Comment by benlev** [comment]
@cabelo, when running rsid-viewer on Windows, are you using the SDK installer or compiling from source?

**Comment by cabelo** [comment]
> @cabelo, when running rsid-viewer on Windows, are you using the SDK installer or compiling from source?

Hi @benlev, i used  the SDK installer

**Comment by cabelo** [comment]
> > @cabelo, when running rsid-viewer on Windows, are you using the SDK installer or compiling from source?
> 
> Hi @benlev, i used the SDK installer

@benlev Other important information, with the parameter RSID_SECURE = 0 enroll and authenticate does not work.

**Comment by benlev** [comment]
@cabelo 
The SDK installer is compiled with RSID_SECURE=0, which means your device must be unpaired to be able to communicate with it.

Since you used the sample keys to pair with your device, you have 2 options:
1. Compile the solution on Windows using RSID_SECURE=1 and run 'rsid-viewer'.
2. Run 'rsid-cli' in your Linux environment, hit 'i' to unpair and 'q' to exit the application. Connect the device to your Windows environment and run the 'rsid-viewer' that was installed with the SDK installer.

**Comment by cabelo** [comment]
@benlev  Thanks, all work now.

I take this opportunity to show that as an openSUSE ambassador and founder of the openSUSE Innovators initiative, I homologated the  RealSenseID on all openSUSE Linux.

See: 
https://news.opensuse.org/ 
https://news.opensuse.org/2021/05/19/RealSenseID-available-for-openSUSE/
https://en.opensuse.org/SDB:Install_RealSenseID
