### ISSUE TITLE
Query Device Config Error

### ISSUE THREAD

**Issue by srijithumakanth** [IntelRealSense/RealSenseID#65]
Every time I connect the device to the RealSense ID Viewer software on windows, it fails to connect and gives me a serial security error also fails to query the device config.

![image](https://user-images.githubusercontent.com/41660311/119099270-5bdbb080-b9dc-11eb-92dc-66d2739ee96d.png)

FW Version: F450_2.8.0.7_SIGNED.bin

**Comment by benlev** [comment]
Is this reproduced when running rsid-viewer after generating the solution with RSID_SECURE=1?
