### ISSUE TITLE
Crash when running rsid-viewer.exe

### ISSUE THREAD

**Issue by wolfysan** [IntelRealSense/RealSenseID#72]
OS: Window 10
Camera: F455
CPU: AMD
-----------------------------------
I just downloaded the latest version v0.18.1, I installed it on my Win 10 PC, and when I run the Intel Realsense Viewer, the window appears, and after a few moments, it closes. 

I checked EventViewer and I saw an error there without to many details:
Application: rsid-viewer.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.AccessViolationException
   at rsid.Authenticator.rsid_is_fw_compatible_with_host(System.String)
   at rsid_wrapper_csharp.MainWindow.QueryDeviceMetadata(rsid.SerialConfig)
   at rsid_wrapper_csharp.MainWindow.DetectDevice()
   at rsid_wrapper_csharp.MainWindow.InitialSession(System.Object)

What could be the cause of this problem?

Thank you.

LE: The crash seems to happen only if the camera is connected. If I disconnect the camera and then launch the Viewer, nothing crashes, but it tells me no device found. So this means the Firmware is to old?

**Comment by 3dsf** [comment]
In my limited experience with this product, I found it is very important to match the firmware version to the sdk version.  
The fw can be found in the assets section, https://github.com/IntelRealSense/RealSenseID/releases

**Comment by gabime** [comment]
There was a recent pr #69 that might be fix this issue as well. Please try to recompile the viewer using latest commit and see if it solves the issue.

**Comment by wolfysan** [comment]
He found that the firmware is old, and we are currently working on updating it.
Depending on what happens after the firmware update, I will return an update this issue.

**Comment by wolfysan** [comment]
Update firmware fixed the issue.
