### ISSUE TITLE
Information

### ISSUE THREAD

**Issue by nawara72** [IntelRealSense/RealSenseID#73]
Sorry this is not an issue but requesting more info.
I am interested in tracking the pose of the face in real time, I notice that their is some facepose computation, can the F455 be used for face pose tracking? if yes, how is it done and how accurate is it?

Thanks

**Comment by gabime** [comment]
Currently, there is no such feature.

**Comment by robbel** [comment]
Could we add a request for that feature or is it unlikely this will make it onto the roadmap? 
Also curious at what frequency the device (internally) detects face poses and thus may be able to stream those.
Thanks!
