### ISSUE TITLE
Error while using C# wrapper

### ISSUE THREAD

**Issue by wolfysan** [IntelRealSense/RealSenseID#74]
Camera: F455
OS: Windows 10
Wrapper: C# (x64 debug build)
------------------------
While using the C# wrapper, I was trying to get the preview functionality to work, and I got an error while calling the CreatePreview method:
`
System.EntryPointNotFoundException: 'Unable to find an entry point named 'rsid_create_preview' in DLL 'rsid_c_debug'.'
`
Other methods like the Authenticator ones work without any issues. Just this one seems to not work.

Anyone else had this problem? Should I rebuild the wrapper in release mode?

Thank you.

**Comment by gabime** [comment]
You need to compiled with -DRSID_PREVIEW=ON to get preview support
