### ISSUE TITLE
undefined reference to `RealSenseID::FaceAuthenticator::FaceAuthenticator()

### ISSUE THREAD

**Issue by zeynepkoyun** [IntelRealSense/RealSenseID#81]
@alexk1976  @RealSenseCustomerSupport  When I try to run enroll.cc I get the error "undefined reference to `RealSenseID::FaceAuthenticator::FaceAuthenticator()".
I would be glad if you help.

**Comment by lmjieSCU** [comment]
maybe you can try as this:
./enroll -l rsid -l rsid_c

**Comment by lmjieSCU** [comment]
the librsid.so and librsid_c.so file you can find in build dir after running

**Comment by lmjieSCU** [comment]
the librsid.so and librsid_c.so file you can find in build dir after running sudo make install

**Comment by zeynepkoyun** [comment]
@lmjieSCU Thanks for your answer, the files you mentioned were created when the compilation was complete but when I tried to run the sample code I got this error
Now I'm looking again.

**Comment by zeynepkoyun** [comment]
> belki şöyle deneyebilirsiniz:
> ./enroll -l rsid -l rsid_c
Hi @lmjieSCU 
Could I be using the above statement incorrectly? I'm trying to run it using the "g++ enroll.cc" command on Linux 16.04.

**Comment by benlev** [comment]
Please try the following:

1. Make sure your device is unpaired.
2. Re-generate the solution with RSID_SECURE=0.
3. Re-compile the enroll.c sample code.

**Comment by zeynepkoyun** [comment]
> Please try the following:
> 
> 1. Make sure your device is unpaired.
> 2. Re-generate the solution with RSID_SECURE=0.
> 3. Re-compile the enroll.c sample code.
@benlev Thanks for your answer, I tried to do as per the above steps but I get the same error.

**Comment by RealSenseSupport** [comment]
when you build the sample, you may need add some arguments.

> -I dir
>     Add the directory dir to the list of directories to be searched for header files during preprocessing.
> -Ldir
>     Add directory dir to the list of directories to be searched for -l.

https://gcc.gnu.org/onlinedocs/gcc/Directory-Options.html

**Comment by gabime** [comment]
@zeynepkoyun Did you managed solve the issue ?
