### ISSUE TITLE
how to fix Serial_SecurityError

### ISSUE THREAD

**Issue by lmjieSCU** [IntelRealSense/RealSenseID#82]
![image](https://user-images.githubusercontent.com/71051781/121023271-b3985b00-c7d5-11eb-949b-c52cbf5b7e0e.png)
whatever FW I update,what I get only was  Serial_SecurityError

**Comment by benlev** [comment]
Are you trying to run with RSID_SECURE enabled?

**Comment by mdisg** [comment]
I also have seen the SecurityError popping up using the C# wrapper with `RSID_SECURE` disabled. It appeared sporadic in very rare cases.

**Comment by mengyui** [comment]
@lmjieSCU I guess you have to run old app with RSID_SECURE enabled, and call UnPair in the app. and than upgrade FW, or run other app without RSID_SECURE enabled.
