### ISSUE TITLE
Compile new program using .so file

### ISSUE THREAD

**Issue by alexossa1** [IntelRealSense/RealSenseID#83]
I have tried to compile a new .cpp file using built librsid.so and librsid_c.so within /RealSenseID/build/lib. but I got  "fatal error: RealSenseID/FaceAuthenticator.h: No such file or directory" 

The command that I am using is:

>>gcc -L. mycppfile.cpp -lrsid -lrsid_c

What could be wrong?

**Comment by alexossa1** [comment]
Do anyone try to compile a owned .cpp using the .so libraries?

**Comment by RealSenseSupport** [comment]
Please add "-I <path_to_include_dir>" to your command line.
https://gcc.gnu.org/onlinedocs/gcc/Directory-Options.html
