### ISSUE TITLE
Connection Error | Intel LiDAR L515

### ISSUE THREAD

**Issue by peymanmajidi** [IntelRealSense/RealSenseID#84]
The camera is connected. but still shows `Connection Error`.
I'm using _Intel RealSense Viewer_ with no problem.   
Need to help
Thanks

![image](https://user-images.githubusercontent.com/24313930/121295618-94e4b200-c904-11eb-9417-8e1ff33e8de5.png)

**Comment by 3dsf** [comment]
I don't think realSenseID is supposed to work with the l515

**Comment by peymanmajidi** [comment]
OK, sad news... is there any plan to support the L500 series?

**Comment by RealSenseSupport** [comment]
RealSense ID viewer only works with F450/F455.
Realsense Viewer works with L515. Please download RealSense viewer at: https://www.intelrealsense.com/sdk-2/#sdk2-tools

**Comment by peymanmajidi** [comment]
OK, thanks
