### ISSUE TITLE
Enroll user with picture

### ISSUE THREAD

**Issue by luca18** [IntelRealSense/RealSenseID#86]
Would it be possible to configure the SDK or modify the source code so that the camera can enroll a person just with a picture of the given person? Right now, when I try to enroll myself with a picture of myself, it says Face Not Detected or Spoofing.

**Comment by alexossa1** [comment]
I think is not possible, the F455 uses the depth camera to extract the face features to compare with the data base

**Comment by 3dsf** [comment]
I'm not with Intel, but I don't think that is in the plan.  What makes this
device special is the biometric security features.

That being said, there is nothing stopping you from triggering a
realsenseID enrollment action based on face recognition using a different
library.

**Comment by alexk1976** [comment]
Hello guys,
The feature is part of our plan and already in development
You will be able to enroll using .png image

**Comment by 3dsf** [comment]
@alexk1976 
Interesting, I assumed it could not done since there was not a conversion mechanism between different models. https://github.com/IntelRealSense/RealSenseID/issues/77  

Does a match with the png trigger an enrolment action, or will the submission of the png be the enrolment action?

**Comment by luca18** [comment]
@alexk1976 
Do you have a timeline for this feature? What would be the approximate release date?

**Comment by alexk1976** [comment]
I assume it's be ready end of next week.
The feature will enable you to send us png image for enrollment only.
Authentication still will require real camera only as before and no plan to enable to authenticate using png images.

**Comment by RealSenseSupport** [comment]
@luca18 You can try EnrollImage API in RSID v0.21.0
https://github.com/IntelRealSense/RealSenseID/releases/tag/v.21.0

**Comment by gabime** [comment]
Supported since version 0.21.0.
