### ISSUE TITLE
Working in host mode with a database.

### ISSUE THREAD

**Issue by TMV-83** [IntelRealSense/RealSenseID#87]
Please show an example in c ++ of saving a database to a file and reading it from it (static std::map<std::string, RealSenseID::Faceprints> s_user_faceprint_db) .

**Comment by alexk1976** [comment]
I assume you find easily  how to write/read binary buffer to/from file in web. Look for fread/fread/fwrite or iftsream APIs.

**Comment by TMV-83** [comment]
Thanks for the valuable advice. If I found a similar example on the Internet, I would not ask.
