### ISSUE TITLE
USB-C to USB-C connection won't work

### ISSUE THREAD

**Issue by tetek** [IntelRealSense/RealSenseID#88]
Hey,

The cable that comes in a package is USB-A to USB-C, which works just fine.
I was trying to connect USB-C to USB-C and that didn't work, is there any reason for it?
I plan to do some investigation but maybe someone here has already done it.

Thanks,
Wojtek

**Comment by RealSenseSupport** [comment]
Hi Wojtek, 
Are you trying USB-A to USB-C convertor? I tried and it works well on my side.

**Comment by tetek** [comment]
yeah, that works fine, still though, would be useful to use just usb-c usb-c in some cases.
