### ISSUE TITLE
Will the library support returning depth image constructed by the F455 device?

### ISSUE THREAD

**Issue by pvhduc97** [IntelRealSense/RealSenseID#89]
I really want to get the depth image for other operations 😄
Is this feature being developed. If not, can you give us the estimated release time for the feature?

**Comment by RealSenseSupport** [comment]
Hi pvhduc97,

F455 does not support to output 'Depth Image'. Thanks!

**Comment by pvhduc97** [comment]
Hello @RealSenseSupport, you mean F455 will never support output 'depth image'?

'depth image' : something similar to this:
![depth_image](https://user-images.githubusercontent.com/32290894/123944843-bb5bb180-d9c7-11eb-8177-f8e96c83fe29.png)

**Comment by RealSenseSupport** [comment]
Hi pvhduc97,

Thanks for detail samples!
But there is no disparity output from F455 either.

**Comment by 3dsf** [comment]
@RealSenseCustomerSupport 

After looking at something like [this piece of marketing](https://www.intelrealsense.com/wp-content/uploads/2020/12/RealSense_Digram_1440px_Wide_v5.mp4) — is there access to mapped data points in which a mesh like that could be overlain?

**Comment by RealSenseSupport** [comment]
The disparity will be used by internal algorithm only.

**Comment by pvhduc97** [comment]
Thank @RealSenseSupport, I got it.
I think due to some security risks for the device, your team cannot provide the disparity map.

**Comment by gabime** [comment]
F455 does not support constructing the depth image.
