### ISSUE TITLE
SecurityError

### ISSUE THREAD

**Issue by luca18** [IntelRealSense/RealSenseID#96]
Hi,

I keep on getting the same error when I start the RealSense ID Viewer Software on Windows 10. The error persists when I try to enroll or authenticate. 

I've updated the firmware to the most recent sku1 version. I think there is a problem with my camera since it's giving me errors everywhere Windows or Ubuntu regardless of everything I try.

Is there a way to hit a 'factory reset' for the camera?

<img width="446" alt="error-message" src="https://user-images.githubusercontent.com/74397375/124950630-97f4c000-dfe0-11eb-8809-eff4a55197ce.PNG">

**Comment by lmjieSCU** [comment]
I got it as well. Have you solved it?Thanks very much

**Comment by gabime** [comment]
Please see https://github.com/IntelRealSense/RealSenseID/issues/47 on possible solution.

**Comment by luca18** [comment]
Thank you @gabime for the reference.
This solved the problem.
