### ISSUE TITLE
Which function to use for the fastest anti-spoofing?

### ISSUE THREAD

**Issue by tetek** [IntelRealSense/RealSenseID#98]
What would be the fastest way to do anti-spoofing? and how fast can it get?
Right now we are using ExtractFaceprintsForAuth,.
I'm asking because I expected  it to work faster when changed from multi to single face, but that had no effect.
Always around 600ms. 

Thanks

**Comment by alexk1976** [comment]
yes, this function is ok. Also you can use Authenticate(). In settings it's recommended to select "Spoof" algo flow and "medium" security level.  We expected to release more optimized version on coming Sunday
